// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_API_GAMMA_API_H_
#define FLATBUFFERS_GENERATED_API_GAMMA_API_H_

#include "flatbuffers/flatbuffers.h"

namespace gamma_api {

struct ResultItem;

struct SearchResult;

struct Response;

enum SearchResultCode {
  SearchResultCode_SUCCESS = 0,
  SearchResultCode_INDEX_NOT_TRAINED = 1,
  SearchResultCode_SEARCH_ERROR = 2,
  SearchResultCode_MIN = SearchResultCode_SUCCESS,
  SearchResultCode_MAX = SearchResultCode_SEARCH_ERROR
};

inline const SearchResultCode (&EnumValuesSearchResultCode())[3] {
  static const SearchResultCode values[] = {
    SearchResultCode_SUCCESS,
    SearchResultCode_INDEX_NOT_TRAINED,
    SearchResultCode_SEARCH_ERROR
  };
  return values;
}

inline const char * const *EnumNamesSearchResultCode() {
  static const char * const names[] = {
    "SUCCESS",
    "INDEX_NOT_TRAINED",
    "SEARCH_ERROR",
    nullptr
  };
  return names;
}

inline const char *EnumNameSearchResultCode(SearchResultCode e) {
  if (e < SearchResultCode_SUCCESS || e > SearchResultCode_SEARCH_ERROR) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSearchResultCode()[index];
}

enum DataType {
  DataType_INT = 0,
  DataType_LONG = 1,
  DataType_FLOAT = 2,
  DataType_DOUBLE = 3,
  DataType_STRING = 4,
  DataType_VECTOR = 5,
  DataType_MIN = DataType_INT,
  DataType_MAX = DataType_VECTOR
};

inline const DataType (&EnumValuesDataType())[6] {
  static const DataType values[] = {
    DataType_INT,
    DataType_LONG,
    DataType_FLOAT,
    DataType_DOUBLE,
    DataType_STRING,
    DataType_VECTOR
  };
  return values;
}

inline const char * const *EnumNamesDataType() {
  static const char * const names[] = {
    "INT",
    "LONG",
    "FLOAT",
    "DOUBLE",
    "STRING",
    "VECTOR",
    nullptr
  };
  return names;
}

inline const char *EnumNameDataType(DataType e) {
  if (e < DataType_INT || e > DataType_VECTOR) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDataType()[index];
}

struct ResultItem FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCORE = 4,
    VT_NAME = 6,
    VT_VALUE = 8,
    VT_SOURCE = 10,
    VT_DATA_TYPE = 12,
    VT_EXTRA = 14
  };
  double score() const {
    return GetField<double>(VT_SCORE, 0.0);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *name() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_NAME);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *value() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_VALUE);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *source() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_SOURCE);
  }
  const flatbuffers::Vector<int8_t> *data_type() const {
    return GetPointer<const flatbuffers::Vector<int8_t> *>(VT_DATA_TYPE);
  }
  const flatbuffers::String *extra() const {
    return GetPointer<const flatbuffers::String *>(VT_EXTRA);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_SCORE) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyVector(name()) &&
           verifier.VerifyVectorOfStrings(name()) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyVector(value()) &&
           verifier.VerifyVectorOfStrings(value()) &&
           VerifyOffset(verifier, VT_SOURCE) &&
           verifier.VerifyVector(source()) &&
           verifier.VerifyVectorOfStrings(source()) &&
           VerifyOffset(verifier, VT_DATA_TYPE) &&
           verifier.VerifyVector(data_type()) &&
           VerifyOffset(verifier, VT_EXTRA) &&
           verifier.VerifyString(extra()) &&
           verifier.EndTable();
  }
};

struct ResultItemBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_score(double score) {
    fbb_.AddElement<double>(ResultItem::VT_SCORE, score, 0.0);
  }
  void add_name(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> name) {
    fbb_.AddOffset(ResultItem::VT_NAME, name);
  }
  void add_value(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> value) {
    fbb_.AddOffset(ResultItem::VT_VALUE, value);
  }
  void add_source(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> source) {
    fbb_.AddOffset(ResultItem::VT_SOURCE, source);
  }
  void add_data_type(flatbuffers::Offset<flatbuffers::Vector<int8_t>> data_type) {
    fbb_.AddOffset(ResultItem::VT_DATA_TYPE, data_type);
  }
  void add_extra(flatbuffers::Offset<flatbuffers::String> extra) {
    fbb_.AddOffset(ResultItem::VT_EXTRA, extra);
  }
  explicit ResultItemBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ResultItemBuilder &operator=(const ResultItemBuilder &);
  flatbuffers::Offset<ResultItem> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ResultItem>(end);
    return o;
  }
};

inline flatbuffers::Offset<ResultItem> CreateResultItem(
    flatbuffers::FlatBufferBuilder &_fbb,
    double score = 0.0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> name = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> value = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> source = 0,
    flatbuffers::Offset<flatbuffers::Vector<int8_t>> data_type = 0,
    flatbuffers::Offset<flatbuffers::String> extra = 0) {
  ResultItemBuilder builder_(_fbb);
  builder_.add_score(score);
  builder_.add_extra(extra);
  builder_.add_data_type(data_type);
  builder_.add_source(source);
  builder_.add_value(value);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<ResultItem> CreateResultItemDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    double score = 0.0,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *name = nullptr,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *value = nullptr,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *source = nullptr,
    const std::vector<int8_t> *data_type = nullptr,
    const char *extra = nullptr) {
  auto name__ = name ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*name) : 0;
  auto value__ = value ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*value) : 0;
  auto source__ = source ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*source) : 0;
  auto data_type__ = data_type ? _fbb.CreateVector<int8_t>(*data_type) : 0;
  auto extra__ = extra ? _fbb.CreateString(extra) : 0;
  return gamma_api::CreateResultItem(
      _fbb,
      score,
      name__,
      value__,
      source__,
      data_type__,
      extra__);
}

struct SearchResult FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TOTAL = 4,
    VT_RESULT_CODE = 6,
    VT_MSG = 8,
    VT_RESULT_ITEMS = 10
  };
  int32_t total() const {
    return GetField<int32_t>(VT_TOTAL, 0);
  }
  SearchResultCode result_code() const {
    return static_cast<SearchResultCode>(GetField<int8_t>(VT_RESULT_CODE, 0));
  }
  const flatbuffers::String *msg() const {
    return GetPointer<const flatbuffers::String *>(VT_MSG);
  }
  const flatbuffers::Vector<flatbuffers::Offset<ResultItem>> *result_items() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<ResultItem>> *>(VT_RESULT_ITEMS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TOTAL) &&
           VerifyField<int8_t>(verifier, VT_RESULT_CODE) &&
           VerifyOffset(verifier, VT_MSG) &&
           verifier.VerifyString(msg()) &&
           VerifyOffset(verifier, VT_RESULT_ITEMS) &&
           verifier.VerifyVector(result_items()) &&
           verifier.VerifyVectorOfTables(result_items()) &&
           verifier.EndTable();
  }
};

struct SearchResultBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_total(int32_t total) {
    fbb_.AddElement<int32_t>(SearchResult::VT_TOTAL, total, 0);
  }
  void add_result_code(SearchResultCode result_code) {
    fbb_.AddElement<int8_t>(SearchResult::VT_RESULT_CODE, static_cast<int8_t>(result_code), 0);
  }
  void add_msg(flatbuffers::Offset<flatbuffers::String> msg) {
    fbb_.AddOffset(SearchResult::VT_MSG, msg);
  }
  void add_result_items(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<ResultItem>>> result_items) {
    fbb_.AddOffset(SearchResult::VT_RESULT_ITEMS, result_items);
  }
  explicit SearchResultBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  SearchResultBuilder &operator=(const SearchResultBuilder &);
  flatbuffers::Offset<SearchResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SearchResult>(end);
    return o;
  }
};

inline flatbuffers::Offset<SearchResult> CreateSearchResult(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t total = 0,
    SearchResultCode result_code = SearchResultCode_SUCCESS,
    flatbuffers::Offset<flatbuffers::String> msg = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<ResultItem>>> result_items = 0) {
  SearchResultBuilder builder_(_fbb);
  builder_.add_result_items(result_items);
  builder_.add_msg(msg);
  builder_.add_total(total);
  builder_.add_result_code(result_code);
  return builder_.Finish();
}

inline flatbuffers::Offset<SearchResult> CreateSearchResultDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t total = 0,
    SearchResultCode result_code = SearchResultCode_SUCCESS,
    const char *msg = nullptr,
    const std::vector<flatbuffers::Offset<ResultItem>> *result_items = nullptr) {
  auto msg__ = msg ? _fbb.CreateString(msg) : 0;
  auto result_items__ = result_items ? _fbb.CreateVector<flatbuffers::Offset<ResultItem>>(*result_items) : 0;
  return gamma_api::CreateSearchResult(
      _fbb,
      total,
      result_code,
      msg__,
      result_items__);
}

struct Response FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RESULTS = 4,
    VT_ONLINE_LOG_MESSAGE = 6
  };
  const flatbuffers::Vector<flatbuffers::Offset<SearchResult>> *results() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<SearchResult>> *>(VT_RESULTS);
  }
  const flatbuffers::String *online_log_message() const {
    return GetPointer<const flatbuffers::String *>(VT_ONLINE_LOG_MESSAGE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_RESULTS) &&
           verifier.VerifyVector(results()) &&
           verifier.VerifyVectorOfTables(results()) &&
           VerifyOffset(verifier, VT_ONLINE_LOG_MESSAGE) &&
           verifier.VerifyString(online_log_message()) &&
           verifier.EndTable();
  }
};

struct ResponseBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_results(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<SearchResult>>> results) {
    fbb_.AddOffset(Response::VT_RESULTS, results);
  }
  void add_online_log_message(flatbuffers::Offset<flatbuffers::String> online_log_message) {
    fbb_.AddOffset(Response::VT_ONLINE_LOG_MESSAGE, online_log_message);
  }
  explicit ResponseBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ResponseBuilder &operator=(const ResponseBuilder &);
  flatbuffers::Offset<Response> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Response>(end);
    return o;
  }
};

inline flatbuffers::Offset<Response> CreateResponse(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<SearchResult>>> results = 0,
    flatbuffers::Offset<flatbuffers::String> online_log_message = 0) {
  ResponseBuilder builder_(_fbb);
  builder_.add_online_log_message(online_log_message);
  builder_.add_results(results);
  return builder_.Finish();
}

inline flatbuffers::Offset<Response> CreateResponseDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<SearchResult>> *results = nullptr,
    const char *online_log_message = nullptr) {
  auto results__ = results ? _fbb.CreateVector<flatbuffers::Offset<SearchResult>>(*results) : 0;
  auto online_log_message__ = online_log_message ? _fbb.CreateString(online_log_message) : 0;
  return gamma_api::CreateResponse(
      _fbb,
      results__,
      online_log_message__);
}

inline const gamma_api::Response *GetResponse(const void *buf) {
  return flatbuffers::GetRoot<gamma_api::Response>(buf);
}

inline const gamma_api::Response *GetSizePrefixedResponse(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<gamma_api::Response>(buf);
}

inline bool VerifyResponseBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<gamma_api::Response>(nullptr);
}

inline bool VerifySizePrefixedResponseBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<gamma_api::Response>(nullptr);
}

inline void FinishResponseBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<gamma_api::Response> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedResponseBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<gamma_api::Response> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace gamma_api

#endif  // FLATBUFFERS_GENERATED_API_GAMMA_API_H_
