#--------------------------------------------
#    GAMMA ENGINE 
#--------------------------------------------
PROJECT(gamma_engine C CXX)
CMAKE_MINIMUM_REQUIRED(VERSION 3.0)


#ENV VARs
SET(THIRD_PARTY_COMMON ${CMAKE_CURRENT_SOURCE_DIR}/3rdparty)
SET(UTIL ${CMAKE_CURRENT_SOURCE_DIR}/util)
SET(GAMMA_SEARCH ${CMAKE_CURRENT_SOURCE_DIR}/search)
SET(GAMMA_INDEX ${CMAKE_CURRENT_SOURCE_DIR}/index)
SET(GAMMA_VECTOR ${CMAKE_CURRENT_SOURCE_DIR}/vector)
SET(GAMMA_REALTIME ${CMAKE_CURRENT_SOURCE_DIR}/realtime)
SET(GAMMA_PROFILE ${CMAKE_CURRENT_SOURCE_DIR}/profile)
SET(GAMMA_CACHE ${CMAKE_CURRENT_SOURCE_DIR}/cache)
SET(GAMMA_C_API ${CMAKE_CURRENT_SOURCE_DIR}/c_api)


SET(CMAKE_CXX_FLAGS_DEBUG "$ENV{CXXFLAGS} -std=c++11 -mavx2 -msse4 -mpopcnt -fopenmp -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE -DOPEN_CORE -O0 -w -g3 -gdwarf-2")
SET(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -std=c++11 -fPIC -m64 -Wall -O3 -mavx2 -msse4 -mpopcnt -fopenmp -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE -Werror=narrowing -Wno-deprecated")
#SET(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -std=c++11 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILE -O3 -Werror -Wno-deprecated -Werror=narrowing")
#INCLUDE DIR
INCLUDE_DIRECTORIES(${UTIL})
INCLUDE_DIRECTORIES(${GAMMA_PROFILE})
INCLUDE_DIRECTORIES(${GAMMA_CACHE})
INCLUDE_DIRECTORIES(${GAMMA_SEARCH})
INCLUDE_DIRECTORIES(${GAMMA_INDEX})
INCLUDE_DIRECTORIES(${GAMMA_VECTOR})
INCLUDE_DIRECTORIES(${GAMMA_REALTIME})
INCLUDE_DIRECTORIES(${GAMMA_C_API})

INCLUDE_DIRECTORIES(${THIRD_PARTY_COMMON}/openssl/include/)
INCLUDE_DIRECTORIES(${THIRD_PARTY_COMMON}/glog/include/)
INCLUDE_DIRECTORIES(${THIRD_PARTY_COMMON}/iconv/include/)
INCLUDE_DIRECTORIES(${THIRD_PARTY_COMMON}/zlib/include/)
INCLUDE_DIRECTORIES(${THIRD_PARTY_COMMON}/faiss/include/)

#LINK LIBRARY
SET(LIBRARIES
    ${THIRD_PARTY_COMMON}/faiss/lib/libfaiss.a
    ${THIRD_PARTY_COMMON}/crypto/lib/libcrypto.a
    ${THIRD_PARTY_COMMON}/glog/lib/libglog.a
    ${THIRD_PARTY_COMMON}/curl/lib/libcurl.a
    ${THIRD_PARTY_COMMON}/zlib/lib/libz.a
    /usr/local/lib/libevent.a
    /usr/lib64/libopenblas.so
    /usr/lib64/libpthread.so
    /usr/lib64/libdl.so
    /usr/lib64/librt.so
)

#ADDITIONAL SOURCE DIR
AUX_SOURCE_DIRECTORY(${UTIL} DIR_SRCS)
AUX_SOURCE_DIRECTORY(${GAMMA_SEARCH} DIR_SRCS)
AUX_SOURCE_DIRECTORY(${GAMMA_INDEX} DIR_SRCS)
AUX_SOURCE_DIRECTORY(${GAMMA_VECTOR} DIR_SRCS)
AUX_SOURCE_DIRECTORY(${GAMMA_REALTIME} DIR_SRCS)
AUX_SOURCE_DIRECTORY(${GAMMA_PROFILE} DIR_SRCS)
AUX_SOURCE_DIRECTORY(${GAMMA_CACHE} DIR_SRCS)

#build index
#AUX_SOURCE_DIRECTORY(${GAMMA_INDEX} BUILD_INDEX_SRCS)
#AUX_SOURCE_DIRECTORY(${UTIL} BUILD_INDEX_SRCS)


SET(LIB_SRCS ${DIR_SRCS})

# ADD DEFINITION
ADD_DEFINITIONS(-DHAVE_NETINET_IN_H)
ADD_DEFINITIONS(-DFINTEGER=int)

IF (CMAKE_BUILD_TYPE STREQUAL "Debug")
    MESSAGE(STATUS "Debug Mode")
    MESSAGE(STATUS "Flags:" ${CMAKE_CXX_FLAGS_DEBUG})
    ADD_DEFINITIONS(-DDEBUG) 
ELSE (CMAKE_BUILD_TYPE STREQUAL "Debug")
    SET(CMAKE_BUILD_TYPE "Release" CACHE STRING "build type" FORCE)
    MESSAGE(STATUS "Release Mode")
    MESSAGE(STATUS "Flags:" ${CMAKE_CXX_FLAGS_RELEASE})
ENDIF (CMAKE_BUILD_TYPE STREQUAL "Debug")

IF (PERFORMANCE_TESTING STREQUAL "ON")
    MESSAGE(STATUS "With preformance testing")
    ADD_DEFINITIONS(-DPERFORMANCE_TESTING) 
ENDIF (PERFORMANCE_TESTING STREQUAL "ON")

#ADD_EXECUTABLE(gamma_server
#        ${DIR_SRCS})
#ADD_EXECUTABLE(build_gamma_index
#        ${BUILD_INDEX_SRCS})

#TARGET_LINK_LIBRARIES(gamma_server ${LIBRARIES})
#TARGET_LINK_LIBRARIES(build_gamma_index ${LIBRARIES})
#SET(EXECUTABLE_OUTPUT_PATH ./)

ADD_LIBRARY(gamma SHARED ${LIB_SRCS})
ADD_LIBRARY(gamma_static STATIC ${LIB_SRCS})

TARGET_LINK_LIBRARIES(gamma ${LIBRARIES})
TARGET_LINK_LIBRARIES(gamma_static ${LIBRARIES})

SET_TARGET_PROPERTIES(gamma PROPERTIES VERSION 1.0 SOVERSION 0)
SET_TARGET_PROPERTIES(gamma_static PROPERTIES OUTPUT_NAME "gamma")

INSTALL(TARGETS gamma gamma_static 
	LIBRARY	DESTINATION	lib 
	ARCHIVE	DESTINATION	lib)

INSTALL(FILES ${GAMMA_C_API}/gamma_api.h DESTINATION include)

ADD_SUBDIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}/tests)
