LIST_DATABASE_URI = "/dbs"
DATABASE_URI = "/dbs/%(database_name)s"  # create or delete database use this uri
LIST_SPACE_URI = "/dbs/%(database_name)s/spaces"
SPACE_URI = '/dbs/%(database_name)s/spaces/%(space_name)s'
UPSERT_DOC_URI = "/document/upsert"
DELETE_DOC_URI = "/document/delete"
SEARCH_DOC_URI = "/document/search"
QUERY_DOC_URI = "/document/query"
INDEX_URI = "/document/index"

AUTH_KEY = "Authorization"

SUCCESS = 0
INTERNAL_ERROR = 1
UNKNOWN_ERROR = 2
AUTHENTICATION_FAILED = 3
RECOVER = 4
TIMEOUT = 5
PARAM_ERROR = 6
CONFIG_ERROR = 7

SPACE_NOT_EXIST = 221

DATABASE_NOT_EXIST = 200
DB_EXIST = 201

MSG_NOT_EXIST = "notexist"

#document 260-279
DOCUMENT_NOT_EXIST = 260
PRIMARY_KEY_IS_INVALID = 261

#filter 300-319
FILTER_OPERATOR_TYPE_ERR = 300
FILTER_CONDITION_OPERATOR_TYPE_ERR = 301

ERR_CODE_UPSERT_INVALID_PARAMS = 400

#document query 440-459
QUERY_ENGINE_ERR = 440
QUERY_INVALID_PARAMS_LENGTH_OF_DOCUMENT_IDS_BEYOND_500 = 441
QUERY_INVALID_PARAMS_SHOULD_HAVE_ONE_OF_DOCUMENT_IDS_OR_FILTER = 442
QUERY_INVALID_PARAMS_SHOULD_NOT_HAVE_VECTOR_FIELD = 443
QUERY_INVALID_PARAMS_BOTH_DOCUMENT_IDS_AND_FILTER = 444
QUERY_RESPONSE_PARSE_ERR = 445

#document search 460-479
SEARCH_INVALID_PARAMS_SHOULD_HAVE_VECTOR_FIELD = 460
SEARCH_ENGINE_ERR = 461
SEARCH_RESPONSE_PARSE_ERR = 462
